apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-reporting
  labels:
    app: backend-reporting
spec:
  replicas: {{ .Values.backendReporting.replicaCount }}
  selector:
    matchLabels:
      app: backend-reporting
  template:
    metadata:
      labels:
        app: backend-reporting
    spec:
      containers:
      - name: backend-reporting
        image: "{{ .Values.backendReporting.image.repository }}:{{ .Values.global.tag }}"
        imagePullPolicy: {{ .Values.backendReporting.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backendReporting.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.backendReporting.readinessProbe.path }}
            port: {{ .Values.backendReporting.containerPort }}
          initialDelaySeconds: {{ .Values.backendReporting.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backendReporting.readinessProbe.periodSeconds }}

