apiVersion: v1
kind: Service
metadata:
  name: backend-echarging
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: {{ .Values.backendEcharging.service.type }}
  ports:
    - port: {{ .Values.backendEcharging.service.port }}
      targetPort: {{ .Values.backendEcharging.service.targetPort }}
      protocol: TCP
  selector:
    app: backend-echarging
