apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-parking
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: backend-parking
spec:
  type: {{ .Values.backendParking.service.type }}
  ports:
    - port: {{ .Values.backendParking.service.port }}
      targetPort: {{ .Values.backendParking.service.targetPort }}
      protocol: TCP
  selector:
    app: backend-parking
