apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-reporting
spec:
  type: {{ .Values.backendReporting.service.type }}
  ports:
    - port: {{ .Values.backendReporting.service.port }}
      targetPort: {{ .Values.backendReporting.service.targetPort }}
      protocol: TCP
  selector:
    app: backend-reporting
