apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-parking
  labels:
    app: backend-parking
spec:
  replicas: {{ .Values.backendParking.replicaCount }}
  selector:
    matchLabels:
      app: backend-parking
  template:
    metadata:
      labels:
        app: backend-parking
    spec:
      containers:
        - name: backend-parking
          image: "{{ .Values.backendParking.image.repository }}:{{ .Values.global.tag }}"
          imagePullPolicy: {{ .Values.backendParking.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backendParking.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backendParking.readinessProbe.path }}
              port: {{ .Values.backendParking.containerPort }}
            initialDelaySeconds: {{ .Values.backendParking.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backendParking.readinessProbe.periodSeconds }}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/firebase/service-account.json
          volumeMounts:
            - name: firebase-credentials
              mountPath: /etc/firebase
              subPath: service-account.json
              readOnly: true
      volumes:
        - name: firebase-credentials
          secret:
            secretName: firebase-credentials
