apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-echarging
  labels:
    app: backend-echarging
spec:
  replicas: {{ .Values.backendEcharging.replicaCount }}
  selector:
    matchLabels:
      app: backend-echarging
  template:
    metadata:
      labels:
        app: backend-echarging
    spec:
      containers:
      - name: backend-echarging
        image: "{{ .Values.backendEcharging.image.repository }}:{{ .Values.global.tag }}"
        imagePullPolicy: {{ .Values.backendEcharging.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backendEcharging.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.backendEcharging.readinessProbe.path }}
            port: {{ .Values.backendEcharging.containerPort }}
          initialDelaySeconds: {{ .Values.backendEcharging.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backendEcharging.readinessProbe.periodSeconds }}
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/firebase/service-account.json
        volumeMounts:
        - name: firebase-credentials
          mountPath: /etc/firebase
          readOnly: true
      volumes:
      - name: firebase-credentials
        secret:
          secretName: firebase-credentials
