backend:
  replicaCount: 1
  image:
    repository: europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-server
    tag: "1.1.1"
    pullPolicy: IfNotPresent
  containerPort: 3015
  readinessProbe:
    path: /api/health
    initialDelaySeconds: 5
    periodSeconds: 10
  service:
    type: ClusterIP
    port: 80
    targetPort: 3015

frontend:
  replicaCount: 2
  image:
    repository: frontend-app
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
