backend:
  replicaCount: 1
  image:
    repository: europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-server
    tag: "1.1.1"
    pullPolicy: IfNotPresent
  containerPort: 3015
  readinessProbe:
    path: /api/health
    initialDelaySeconds: 5
    periodSeconds: 10
  service:
    type: ClusterIP
    port: 80
    targetPort: 3015

backend-echarging:
  replicaCount: 1
  image:
    repository: europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-echarging
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  containerPort: 3016
  readinessProbe:
    path: /api/echarging/health
    initialDelaySeconds: 5
    periodSeconds: 10
  service:
    type: ClusterIP
    port: 80
    targetPort: 3016

frontend:
  replicaCount: 1
  image:
    repository: europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/frontend-server
    tag: "1.1.1"
    pullPolicy: Always
  containerPort: 3000
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

ingress:
  enabled: true
