global:
  tag: "latest"

backend:
  replicaCount: 2
  image:
    repository: europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-server
    tag: "{{ .Values.global.tag }}"
    pullPolicy: Always
  containerPort: 3015
  readinessProbe:
    path: /api/health
    initialDelaySeconds: 5
    periodSeconds: 10
  service:
    type: ClusterIP
    port: 80
    targetPort: 3015

backendEcharging:
  replicaCount: 2
  image:
    repository: europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-echarging-server
    tag: "{{ .Values.global.tag }}"
    pullPolicy: Always
  containerPort: 3016
  readinessProbe:
    path: /api/echarging/health
    initialDelaySeconds: 5
    periodSeconds: 10
  service:
    type: ClusterIP
    port: 80
    targetPort: 3016

backendParking:
  replicaCount: 2
  image:
    repository: europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-parking-server
    tag: "{{ .Values.global.tag }}"
    pullPolicy: Always
  containerPort: 3033
  readinessProbe:
    path: /api/parking/health
    initialDelaySeconds: 5
    periodSeconds: 10
  service:
    type: ClusterIP
    port: 80
    targetPort: 3033

backendReporting:
  replicaCount: 2
  image:
    repository: europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-reporting-server
    tag: "{{ .Values.global.tag }}"
    pullPolicy: IfNotPresent
  containerPort: 3004
  readinessProbe:
    path: /api/reporting/health
    initialDelaySeconds: 5
    periodSeconds: 10
  service:
    type: ClusterIP
    port: 80
    targetPort: 3004

backendFacilityManagement:
  replicaCount: 2
  image:
    repository: europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/facility-management-server
    tag: "{{ .Values.global.tag }}"
    pullPolicy: IfNotPresent
  containerPort: 3021
  readinessProbe:
    path: /api/facilities/health
    initialDelaySeconds: 5
    periodSeconds: 10
  service:
    type: ClusterIP
    port: 80
    targetPort: 3021   

frontend:
  replicaCount: 1
  image:
    repository: europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/frontend-server
    tag: "{{ .Values.global.tag }}"
    pullPolicy: IfNotPresent
  containerPort: 3000
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

ingress:
  enabled: true
