name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - never-run

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Authenticate Docker with Google Cloud
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev

    # Build and push Docker image for Backend
    - name: Build Backend Docker image
      run: |
        docker build --build-arg BUCKET_ENV=_prod -t backend-server:latest -f backend/Dockerfile ./backend

    - name: Tag Backend Docker Image
      run: |
        docker tag backend-server:latest europe-west1-docker.pkg.dev/trabantparking-prod/docker-repo/backend-server:latest

    - name: Push Backend Docker image
      run: |
        docker push europe-west1-docker.pkg.dev/trabantparking-prod/docker-repo/backend-server:latest

    # Deploy Backend to Cloud Run
    - name: Deploy Backend to Cloud Run
      id: deploy-backend
      run: |
        gcloud run deploy trabbiback \
          --image=europe-west1-docker.pkg.dev/trabantparking-prod/docker-repo/backend-server:latest \
          --platform=managed \
          --region=europe-west1 \
          --allow-unauthenticated \
          --port=3015 \
          --memory=1Gi

    # Get Backend URL
    - name: Get Backend URL
      id: get-backend-url
      run: |
        BACKEND_URL=$(gcloud run services describe trabbiback --platform managed --region europe-west1 --format 'value(status.url)')
        echo "BACKEND_URL=${BACKEND_URL}" >> $GITHUB_ENV

    # Build Frontend Docker image with Backend URL as build argument
    - name: Build Frontend Docker image
      run: |
        docker build --build-arg REACT_APP_BACKEND_URL=${{ env.BACKEND_URL }} --build-arg AUTH_API_KEY=${{ secrets.AUTH_API_KEY_PROD }} -t frontend-server:1.1.1 -f frontend/Dockerfile ./frontend

    # Tag and push the image as before
    - name: Tag Frontend Docker Image
      run: |
        docker tag frontend-server:1.1.1 europe-west1-docker.pkg.dev/trabantparking-prod/docker-repo/frontend-server:1.1.1

    - name: Push Frontend Docker image
      run: |
        docker push europe-west1-docker.pkg.dev/trabantparking-prod/docker-repo/frontend-server:1.1.1

    # Deploy Frontend to Cloud Run with Backend URL as environment variable
    - name: Deploy Frontend to Cloud Run
      run: |
        gcloud run deploy trabbifront \
          --image=europe-west1-docker.pkg.dev/trabantparking-prod/docker-repo/frontend-server:1.1.1 \
          --platform=managed \
          --region=europe-west1 \
          --allow-unauthenticated \
          --port=3000 \
          --memory=1Gi \
          --set-env-vars REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}
