name: Deploy Tenant Services

on:
  push:
    branches: [ stage ]
    paths:
      - 'microservices/tenant-creation-frontend/**'
      - 'microservices/backend-tenant-creation/**'
      - '.github/workflows/deploy-tenant-services.yml'

env:
  PROJECT_ID: trabantparking-stage
  BACKEND_IMAGE: backend-tenant-creation
  FRONTEND_IMAGE: tenant-creation-frontend
  REGION: europe-west1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_STAGE }}
          project_id: trabantparking-stage

      - name: Configure Docker
        run: gcloud auth configure-docker

      # Build and push backend
      - name: Build Backend
        run: |
          cd microservices/backend-tenant-creation
          docker build -t ${{ env.BACKEND_IMAGE }} .
          docker tag ${{ env.BACKEND_IMAGE }} ${{ env.PROJECT_ID }}/docker-repo/${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          docker push ${{ env.PROJECT_ID }}/docker-repo/${{ env.BACKEND_IMAGE }}:${{ github.sha }}

      # Deploy backend to Cloud Run
      - name: Deploy Backend to Cloud Run
        id: deploy-backend
        run: |
          gcloud run deploy backend-tenant-creation \
                --image=${{ env.PROJECT_ID }}/docker-repo/${{ env.BACKEND_IMAGE }}:${{ github.sha }} \
                --platform=managed \
                --region=${{ env.REGION }} \
                --allow-unauthenticated \
                --port=3023 \
                --memory=1Gi \
                --env-vars=GOOGLE_CLOUD_PROJECT=${{ env.PROJECT_ID }} \
                --env-vars=GITHUB_TOKEN=${{ secrets.TOKEN }}

      # Build frontend with backend URL
      - name: Build Frontend
        env:
          VITE_BACKEND_URL: ${{ steps.deploy-backend.outputs.url }}
          VITE_AUTH_API_KEY: ${{ secrets.AUTH_API_KEY_STAGE }}
        run: |
          cd microservices/tenant-creation-frontend
          docker build \
            --build-arg VITE_BACKEND_URL=${{ steps.deploy-backend.outputs.url }} \
            --build-arg VITE_AUTH_API_KEY=${{ secrets.AUTH_API_KEY_STAGE }} \
            -t ${{ env.FRONTEND_IMAGE }} .
          docker tag ${{ env.FRONTEND_IMAGE }} ${{ env.PROJECT_ID }}/docker-repo/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          docker push ${{ env.PROJECT_ID }}/docker-repo/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

      # Deploy frontend to Cloud Run
      - name: Deploy Frontend to Cloud Run
        id: deploy-frontend
        run: |
          gcloud run deploy tenant-creation-frontend \
                --image=${{ env.PROJECT_ID }}/docker-repo/${{ env.FRONTEND_IMAGE }}:${{ github.sha }} \
                --platform=managed \
                --region=${{ env.REGION }} \
                --allow-unauthenticated \
                --port=8080 \
                --memory=1Gi

      # Output the URLs
      - name: Output Service URLs
        run: |
          echo "Backend URL: ${{ steps.deploy-backend.outputs.url }}"
          echo "Frontend service deployed successfully"
