name: GCP Kubernetes Deployment

on:
  push:
    branches:
      - kubernetes-creation-pipeline
  workflow_dispatch:  

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: terraform-cluster
  GKE_REGION: europe-west1
  TF_PLAN_BUCKET: ${{ secrets.GCP_PROJECT_ID }}-terraform-plans
  TF_PLAN_FILE: terraform-plan-${{ github.sha }}.tfplan

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_STAGE }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for GCP Artifact Registry
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Create Terraform Plan Bucket
      run: |
        gsutil mb -p ${{ env.PROJECT_ID }} -l ${{ env.GKE_REGION }} gs://${{ env.TF_PLAN_BUCKET }} || true

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.7"

    - name: Initialize Terraform
      run: |
        terraform init
      working-directory: cloud/terraform

    - name: Terraform Plan
      run: |
        terraform plan -out=tfplan
        terraform show -json tfplan > tfplan.json
        gcloud storage cp tfplan.json gs://${{ env.TF_PLAN_BUCKET }}/${{ env.TF_PLAN_FILE }}
      working-directory: cloud/terraform

    - name: Download Previous Plan
      run: |
        gcloud storage cp gs://${{ env.TF_PLAN_BUCKET }}/${{ env.TF_PLAN_FILE }} tfplan.json
      working-directory: cloud/terraform

    - name: Terraform Apply
      run: |
        terraform show -json tfplan.json | terraform apply -auto-approve
      working-directory: cloud/terraform

    - name: Install GKE Auth Plugin
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --region ${{ env.GKE_REGION }}

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.12.3'

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install trabi-app ./helm/trabi-app \
          --namespace trabi-app \
          --create-namespace \
          --wait \
          --timeout 10m0s

    - name: Verify Deployment
      run: |
        kubectl get pods -n trabi-app
        kubectl get services -n trabi-app
