name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - stage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_STAGE }}'

    - name: Authenticate Docker with Google Cloud
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev

    # build backend-echarging image
    - name: Build backend-echarging Docker image
      run: |
        docker build -t backend-echarging-server:1.1.1 -f backend-echarging/Dockerfile ./backend-echarging

    - name: Tag backend-echarging Docker Image
      run: |
        docker tag backend-echarging-server:1.1.1 europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-echarging-server:1.1.1

    - name: Push backend-echarging Docker image
      run: |
        docker push europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-echarging-server:1.1.1

    # build backend-reporting image
    - name: Build backend-reporting Docker image
      run: |
        docker build --build-arg AUTH_API_KEY=${{ secrets.AUTH_API_KEY_STAGE }} --build-arg PROJECT_ID=trabantparking-stage -t backend-reporting-server:1.1.1 -f backend-reporting/Dockerfile ./backend-reporting

    - name: Tag backend-reporting Docker Image
      run: |
        docker tag backend-reporting-server:1.1.1 europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-reporting-server:1.1.1

    - name: Push backend-reporting Docker image
      run: |
        docker push europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-reporting-server:1.1.1