name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Authenticate Docker with Google Cloud bidde jz
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev

    # Build and push Docker image for Frontend
    - name: Build Frontend Docker image
      run: |
        docker build -t frontend-server:1.1.1 -f frontend/Dockerfile ./frontend

    - name: Tag Docker image
      run: |
        docker tag frontend-server:1.1.1 europe-west1-docker.pkg.dev/trabantparking-prod/docker-repo/frontend-server:1.1.1

    - name: Push Frontend Docker image
      run: |
        docker push europe-west1-docker.pkg.dev/trabantparking-prod/docker-repo/frontend-server:1.1.1

    # Deploy Frontend to Cloud Run
    - name: Deploy Frontend to Cloud Run
      run: |
        gcloud run deploy trabbifront --image=europe-west1-docker.pkg.dev/trabantparking-prod/docker-repo/frontend-server:1.1.1 --platform=managed --region=europe-west1 --allow-unauthenticated --port=3000 --memory=1Gi

    # Build and push Docker image for Backend
    - name: Build Backend Docker image
      run: |
        docker build -t backend-server:latest -f backend/Dockerfile ./backend

    - name: Tag Docker Image
      run: |
        docker tag backend-server:latest europe-west1-docker.pkg.dev/trabantparking-prod/docker-repo/backend-server:latest

    - name: Push Backend Docker image
      run: |
        docker push europe-west1-docker.pkg.dev/trabantparking-prod/docker-repo/backend-server:latest

    # Deploy Backend to Cloud Run
    - name: Deploy Backend to Cloud Run
      run: |
        gcloud run deploy trabbiback --image=europe-west1-docker.pkg.dev/trabantparking-prod/docker-repo/backend-server:latest --platform=managed --region=europe-west1 --allow-unauthenticated --port=3015 --memory=1Gi
