name: Production Cluster Creation

on:
  push:
    branches:
      - master

jobs:
  create-free:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt install gh -y

      - name: Trigger another pipeline
        run: |
          gh workflow run cluster-create-k8s.yml -f tenant_name=free -f region=europe-west1 -f zone=europe-west1-a  -R Joschka-ctrl/CloudApplikTrabi -r master
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}  
  
  create-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt install gh -y

      - name: Trigger another pipeline
        run: |
          gh workflow run cluster-create-k8s.yml -f tenant_name=pro -f region=europe-west1 -f zone=europe-west1-a -R Joschka-ctrl/CloudApplikTrabi -r master
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}