name: Production Cluster Creation

on:
  push:
    tags:
      - '1.*' 

jobs:
  create-free:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo $GH_TOKEN | gh auth login --with-token

      - name: Trigger another pipeline
        run: |
          gh workflow run cluster-create-k8s.yml -f tenant_name=free -R Joschka-ctrl/CloudApplikTrabi