name: Stage Cluster Creation

on:
  push:
    tags:
      - '0.*'

jobs:
  build-and-deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Full Cluster Creation
        uses: actions/github-script@v6
        with:
          script: |
            const github = require('@actions/github');
            const octokit = github.getOctokit(process.env.TENANT_CREATION_CLOUD_TOKEN);  // Verwende dein benutzerdefiniertes Token aus den GitHub Secrets

            try {
                // Trigger des Workflows
                const response = await octokit.actions.createWorkflowDispatch({
                    owner: context.repo.owner,  // Dynamisch den Repository Besitzer ermitteln
                    repo: context.repo.repo,
                    workflow_id: 'cluster-create-k8s.yml',  // Die zu startende Workflow-Datei
                    ref: 'refs/heads/main',  // Branch, von dem der Workflow ausgelöst wird
                    inputs: {
                        tenant_name: 'stage'  // Eingabewert für den ausgelösten Workflow
                    }
                });

                console.log('Workflow erfolgreich ausgelöst:', response);
                return true;
            } catch (error) {
                console.error('Fehler beim Auslösen des Workflows:', error);
                throw error;
            }
