name: Stage Cluster Creation

on:
  push:
    branches:
      - stage-cluster 

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: stage-cluster
  GKE_REGION: europe-west1
  TF_PLAN_BUCKET: trabantparking-stage-terraform-plans
  TF_PLAN_FILE: terraform.tfstate
  BUCKET_TF_STATE: trabantparking-stage-terraform-plans/terraform.tfstate

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_STAGE }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for GCP Artifact Registry
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.7"

    - name: Initialize Terraform
      run: |
        terraform init
      working-directory: cloud/terraform

    - name: Check if Cluster Exists
      id: check_cluster
      run: |
        if gcloud container clusters describe ${{ env.GKE_CLUSTER }} --region ${{ env.GKE_REGION }}; then
          echo "Cluster exists"
          echo "CLUSTER_EXISTS=true" >> $GITHUB_ENV
        else
          echo "Cluster does not exist"
          echo "CLUSTER_EXISTS=false" >> $GITHUB_ENV
        fi

    - name: Import Existing Cluster
      if: env.CLUSTER_EXISTS == 'true'
      run: |
        terraform import google_container_cluster.gke projects/${{ env.PROJECT_ID }}/locations/${{ env.GKE_REGION }}/clusters/${{ env.GKE_CLUSTER }}
      working-directory: cloud/terraform

    - name: Cluster Name
      run: |
        echo ${{ env.GKE_CLUSTER }}

    - name: Import Bucket
      run: |
        terraform import google_storage_bucket.default trabantparking-stage-terraform-plans
      working-directory: cloud/terraform  

    - name: Terraform Plan
      run: |
        terraform plan -var="cluster_name=${{ env.GKE_CLUSTER }}" -out=tfplan
        terraform show -json tfplan > plan.json
        gcloud storage cp tfplan gs://${{ env.TF_PLAN_BUCKET }}/${{ env.TF_PLAN_FILE }}
      working-directory: cloud/terraform


    - name: Terraform Apply
      run: |
          if [ -f "tfplan" ]; then
            terraform apply tfplan
          else
            terraform apply -auto-approve
          fi
      working-directory: cloud/terraform

    - name: Migrate Terraform State to Google Cloud Storage
      run: |
        terraform init -migrate-state

    - name: Install GKE Auth Plugin
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --region ${{ env.GKE_REGION }}

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.12.3'

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install trabant-app ./cloud/yamls/helm-chart --namespace default --create-namespace

    - name: Verify Deployment
      run: |
        kubectl get pods -n trabi-app
        kubectl get services -n trabi-app