name: Production Cluster Creation

on:
  push:
    tags:
      - '0.*' 

jobs:
  create-prod-free:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt install gh -y

      - name: Trigger another pipeline
        run: |
          gh workflow run cluster-create-k8s.yml -f tenant_name=stage-free -f region=europe-west1 -f zone=europe-west1-c -R Joschka-ctrl/CloudApplikTrabi -r stage-cluster
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}  

  create-prod-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt install gh -y

      - name: Trigger another pipeline
        run: |
          gh workflow run cluster-create-k8s.yml -f tenant_name=stage-pro -f region=europe-west1 -f zone=europe-west1-c -R Joschka-ctrl/CloudApplikTrabi -r stage-cluster

        env:
          GH_TOKEN: ${{ secrets.TOKEN }}