name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - 
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'backend-echarging/**'
      - 'backend-reporting/**'
      - 'backend-parking/**'
      - '.github/workflows/microservice-docker.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        run: |
          echo "::set-output name=frontend::$(git diff --name-only HEAD^ HEAD | grep ^frontend/ || true)"
          echo "::set-output name=backend::$(git diff --name-only HEAD^ HEAD | grep ^backend/ || true)"
          echo "::set-output name=backend_echarging::$(git diff --name-only HEAD^ HEAD | grep ^backend-echarging/ || true)"
          echo "::set-output name=backend_reporting::$(git diff --name-only HEAD^ HEAD | grep ^backend-reporting/ || true)"
          echo "::set-output name=backend_parking::$(git diff --name-only HEAD^ HEAD | grep ^backend-parking/ || true)"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_STAGE }}'

      - name: Authenticate Docker with Google Cloud
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      # Frontend
      - name: Build and Push Frontend
        if: steps.changed-files.outputs.frontend != ''
        run: |
          docker build \
            --build-arg REACT_APP_BACKEND_URL=/api \
            --build-arg AUTH_API_KEY=${{ secrets.AUTH_API_KEY_STAGE }} \
            -t frontend-server:1.1.1 \
            -f frontend/Dockerfile ./frontend
          docker tag frontend-server:1.1.1 \
            europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/frontend-server:1.1.1
          docker push \
            europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/frontend-server:1.1.1

      # Backend
      - name: Build and Push Backend
        if: steps.changed-files.outputs.backend != ''
        run: |
          docker build \
            --build-arg BUCKET_ENV=_stage \
            -t backend-server:latest \
            -f backend/Dockerfile ./backend
          docker tag backend-server:latest \
            europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-server:latest
          docker push \
            europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-server:latest

      # Backend E-Charging
      - name: Build and Push Backend E-Charging
        if: steps.changed-files.outputs.backend_echarging != ''
        run: |
          docker build \
            --build-arg AUTH_API_KEY=${{ secrets.AUTH_API_KEY_STAGE }} \
            --build-arg PROJECT_ID=trabantparking-stage \
            -t backend-echarging-server:1.1.1 \
            -f backend-echarging/Dockerfile ./backend-echarging
          docker tag backend-echarging-server:1.1.1 \
            europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-echarging-server:1.1.1
          docker push \
            europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-echarging-server:1.1.1

      # Backend Reporting
      - name: Build and Push Backend Reporting
        if: steps.changed-files.outputs.backend_reporting != ''
        run: |
          docker build \
            --build-arg AUTH_API_KEY=${{ secrets.AUTH_API_KEY_STAGE }} \
            --build-arg PROJECT_ID=trabantparking-stage \
            -t backend-reporting-server:1.1.1 \
            -f backend-reporting/Dockerfile ./backend-reporting
          docker tag backend-reporting-server:1.1.1 \
            europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-reporting-server:1.1.1
          docker push \
            europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-reporting-server:1.1.1

      # Backend Parking
      - name: Build and Push Backend Parking
        if: steps.changed-files.outputs.backend_parking != ''
        run: |
          docker build \
            --build-arg AUTH_API_KEY=${{ secrets.AUTH_API_KEY_STAGE }} \
            --build-arg PROJECT_ID=trabantparking-stage \
            -t backend-parking-server:1.1.1 \
            -f backend-parking/Dockerfile ./backend-parking
          docker tag backend-parking-server:1.1.1 \
            europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-parking-server:1.1.1
          docker push \
            europe-west1-docker.pkg.dev/trabantparking-stage/docker-repo/backend-parking-server:1.1.1