name: Production Cluster Update Enterprise Tenants

on:
  push:
    tags:
      - '2.*' 

jobs:
  update-Enterprise-tenants:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_STAGE }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
  
      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
  
      - name: Get list of clusters
        run: |
          clusters=$(gcloud container clusters list --format="value(name)")

          if [ -z "$clusters" ]; then
            echo "No clusters found."
            exit 0
            fi

          echo "Clusters found: $clusters"
          echo "$clusters" > clusters.txt
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))   
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
      - name: Trigger workflow for each cluster
        run: |
          while read -r cluster_name; do
            echo "Triggering workflow for cluster: $cluster_name"
          gh workflow run cluster-create-k8s.yml -f tenant_name=${cluster_name} -f tag=$LATEST_TAG -R Joschka-ctrl/CloudApplikTrabi
          done < clusters.txt
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}